### ISSUE TITLE
compare-revisions sometimes does not list changes for cortex services

### ISSUE THREAD

**Issue by leth** [weaveworks-experiments/compare-revisions#21]
If one service has been updated, the others sometimes stop showing changes

**Comment by rade** [comment]
I thought the particular incident that prompted the filing of this issue pertained to scope.

**Comment by leth** [comment]
Ah, I think perhaps I made a mistake with both? I'm not sure

**Comment by jml** [comment]
I *think* this is just a bug in the config file, in that it's too restrictive about what directories belong to which services.

Easy fix is to get rid of the directories. Hard-core fix is to use Bazel dep information to reverse the dependency graph from the built image and use that as filter.

**Comment by jml** [comment]
Don't think this is a bug in compare-revisions per se. There's an implicit feature request to do proper commit tracking, but that's out of scope for this project.
